unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

bind '"' split-window -h -c '#{pane_current_path}'
bind % split-window -v -c '#{pane_current_path}'

set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-position bottom
set -g status-style fg=white,bg=black
set -g allow-rename on
set-option -g status-interval 1
set -g window-status-format         "#[fg=red,bold][#[default]#I #W #{=|-24|…;s|$HOME|~|:pane_current_path}#[fg=red,bold]]"
set -g window-status-current-format "#[fg=red,bg=white,bold][#[fg=black,bg=white,bold]#I #W #{=|-24|…;s|$HOME|~|:pane_current_path}#[fg=red,bg=white,bold]]"

