unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-position bottom
set -g status-style fg=white,bg=black
set-window-option -g window-status-current-style fg=black,bg=white,bright
